# Generated by Django 4.2 on 2024-05-16 21:26

import api.research_document
import api.source_json_for_db
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30)),
                ('file_content', models.FileField(blank=True, null=True, storage=api.research_document.Over_write_storage, upload_to=api.research_document.get_file_path)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=12)),
                ('bureau_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sync_from_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('source_name', models.CharField(max_length=30)),
                ('file_content', models.FileField(blank=True, null=True, storage=api.source_json_for_db.Over_write_storage, upload_to=api.source_json_for_db.get_file_path)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='URL_to_be_accessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_URL', models.URLField()),
                ('resource', models.IntegerField(null=True)),
                ('bureau_code', models.CharField(max_length=10)),
                ('modified_on', models.DateField(null=True)),
                ('identifier', models.TextField(null=True)),
                ('access_level', models.TextField(null=True)),
                ('program_code', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('media_type', models.TextField(null=True)),
                ('distribution_type', models.TextField(null=True)),
                ('distribution_title', models.TextField(null=True)),
                ('publisher_name', models.TextField(null=True)),
                ('publisher_type', models.TextField(null=True)),
                ('contact_point_email', models.TextField(null=True)),
                ('contact_point_type', models.TextField(null=True)),
                ('contact_point_fn', models.TextField(null=True)),
                ('license', models.TextField(null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_status', models.CharField(default='initial', max_length=10)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('last_error_message', models.TextField(default='N/A')),
                ('next_due_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Download_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('error_message', models.TextField(default='N/A')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.url_to_be_accessed')),
            ],
        ),
    ]
