# Generated by Django 4.2 on 2024-03-04 10:04

import api.research_document
import api.source_json
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sync_from_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('source_name', models.CharField(max_length=30)),
                ('file_content', models.FileField(blank=True, null=True, storage=api.source_json.Over_write_storage(), upload_to=api.source_json.get_file_path)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='URL_to_be_accessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_URL', models.URLField()),
                ('bureau_code', models.CharField(max_length=10)),
                ('modified_on', models.DateField()),
                ('identifier', models.TextField()),
                ('access_level', models.TextField()),
                ('program_code', models.TextField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('media_type', models.TextField()),
                ('distribution_type', models.TextField()),
                ('distribution_title', models.TextField()),
                ('publisher_name', models.TextField()),
                ('publisher_type', models.TextField()),
                ('contact_point_email', models.TextField()),
                ('contact_point_type', models.TextField()),
                ('contact_point_fn', models.TextField()),
                ('last_accessed_status', models.CharField(default='initial', max_length=10)),
                ('last_accessed_at', models.DateTimeField(default=datetime.datetime(2024, 3, 4, 15, 34, 58, 665585))),
                ('next_due_date', models.DateTimeField(null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sync_from_source')),
            ],
        ),
        migrations.CreateModel(
            name='Research_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30)),
                ('file_content', models.FileField(blank=True, null=True, storage=api.research_document.Over_write_storage(), upload_to=api.research_document.get_file_path)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=12)),
                ('bureau_code', models.CharField(max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.url_to_be_accessed')),
            ],
        ),
    ]
