# Generated by Django 4.2 on 2024-06-03 02:27

import api.research_document
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30)),
                ('file_content', models.FileField(blank=True, null=True, storage=api.research_document.Over_write_storage, upload_to=api.research_document.get_file_path)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=12)),
                ('bureau_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
