# Generated by Django 4.2 on 2024-03-04 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 15, 35, 15, 127293)),
        ),
    ]
