# Generated by Django 4.2 on 2024-04-02 16:01

import api.research_document
import api.source_json_for_db
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research_document',
            name='source',
        ),
        migrations.AddField(
            model_name='url_to_be_accessed',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 16, 1, 50, 815622, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url_to_be_accessed',
            name='last_error_message',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='url_to_be_accessed',
            name='license',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='research_document',
            name='bureau_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='research_document',
            name='file_content',
            field=models.FileField(blank=True, null=True, storage=api.research_document.Over_write_storage, upload_to=api.research_document.get_file_path),
        ),
        migrations.AlterField(
            model_name='sync_from_source',
            name='file_content',
            field=models.FileField(blank=True, null=True, storage=api.source_json_for_db.Over_write_storage, upload_to=api.source_json_for_db.get_file_path),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='access_level',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='contact_point_email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='contact_point_fn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='contact_point_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='distribution_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='distribution_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='identifier',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='media_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='modified_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='program_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='publisher_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='publisher_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='resource',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Download_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('error_message', models.TextField(default='N/A')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.url_to_be_accessed')),
            ],
        ),
    ]
