# Generated by Django 4.2 on 2024-03-04 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_url_to_be_accessed_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_to_be_accessed',
            name='license',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 11, 36, 354525)),
        ),
    ]
