# Generated by Django 4.2 on 2024-03-04 12:07

import api.research_document
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_url_to_be_accessed_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research_document',
            name='file_content',
            field=models.FileField(blank=True, null=True, storage=api.research_document.Over_write_storage, upload_to=api.research_document.get_file_path),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 37, 15, 108441)),
        ),
    ]
