# Generated by Django 4.2 on 2024-03-04 12:10

import api.source_json
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_research_document_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync_from_source',
            name='file_content',
            field=models.FileField(blank=True, null=True, storage=api.source_json.Over_write_storage, upload_to=api.source_json.get_file_path),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 40, 57, 567507)),
        ),
    ]
