# Generated by Django 4.2 on 2024-03-04 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sync_from_source_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 17, 44, 17, 508602)),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='resource',
            field=models.IntegerField(null=True),
        ),
    ]
