# Generated by Django 4.2 on 2024-03-18 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_url_to_be_accessed_last_accessed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 22, 53, 42, 40822)),
        ),
    ]
