# Generated by Django 4.2 on 2024-03-22 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_url_to_be_accessed_last_accessed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 23, 19, 53, 972030)),
        ),
    ]
