# Generated by Django 4.2 on 2024-03-23 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_url_to_be_accessed_last_accessed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_to_be_accessed',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 23, 6, 46, 59, 105367, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_accessed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
