# Generated by Django 4.2 on 2024-03-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_url_to_be_accessed_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_to_be_accessed',
            name='last_error_message',
            field=models.TextField(default=True),
        ),
    ]
