# Generated by Django 4.2 on 2024-03-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_url_to_be_accessed_last_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_history',
            name='error_message',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='url_to_be_accessed',
            name='last_error_message',
            field=models.TextField(default='N/A'),
        ),
    ]
